apiVersion: v1
kind: PersistentVolume
metadata:
  name: flg-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy:
    Retain
  nfs:
    path: /mnt/flg
    server: 192.168.1.15
    readOnly: false
